import { Extinguisher } from './types';

export const mockExtinguishers: Extinguisher[] = [
  // 한라산 (제주)
  {
    id: 1,
    name: '한라산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 95,
    extinguisherStatus: 'normal',
    latitude: 33.36167 + (Math.random() - 0.5) * 0.05,
    longitude: 126.52917 + (Math.random() - 0.5) * 0.05,
    region: '제주',
  },
  {
    id: 2,
    name: '한라산 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 30,
    extinguisherStatus: 'normal',
    latitude: 33.36167 + (Math.random() - 0.5) * 0.05,
    longitude: 126.52917 + (Math.random() - 0.5) * 0.05,
    region: '제주',
  },
  {
    id: 3,
    name: '한라산 자동소화기 C',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 33.36167 + (Math.random() - 0.5) * 0.05,
    longitude: 126.52917 + (Math.random() - 0.5) * 0.05,
    region: '제주',
  },
  {
    id: 4,
    name: '한라산 자동소화기 D',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 70,
    extinguisherStatus: 'normal',
    latitude: 33.36167 + (Math.random() - 0.5) * 0.05,
    longitude: 126.52917 + (Math.random() - 0.5) * 0.05,
    region: '제주',
  },
  {
    id: 5,
    name: '한라산 자동소화기 E',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 50,
    extinguisherStatus: 'normal',
    latitude: 33.36167 + (Math.random() - 0.5) * 0.05,
    longitude: 126.52917 + (Math.random() - 0.5) * 0.05,
    region: '제주',
  },

  // 지리산 (경남)
  {
    id: 6,
    name: '지리산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 85,
    extinguisherStatus: 'normal',
    latitude: 35.33694 + (Math.random() - 0.5) * 0.05,
    longitude: 127.73056 + (Math.random() - 0.5) * 0.05,
    region: '경남',
  },
  {
    id: 7,
    name: '지리산 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 20,
    extinguisherStatus: 'normal',
    latitude: 35.33694 + (Math.random() - 0.5) * 0.05,
    longitude: 127.73056 + (Math.random() - 0.5) * 0.05,
    region: '경남',
  },
  {
    id: 8,
    name: '지리산 자동소화기 C',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 35.33694 + (Math.random() - 0.5) * 0.05,
    longitude: 127.73056 + (Math.random() - 0.5) * 0.05,
    region: '경남',
  },
  {
    id: 9,
    name: '지리산 자동소화기 D',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 60,
    extinguisherStatus: 'normal',
    latitude: 35.33694 + (Math.random() - 0.5) * 0.05,
    longitude: 127.73056 + (Math.random() - 0.5) * 0.05,
    region: '경남',
  },

  // 설악산 (강원)
  {
    id: 10,
    name: '설악산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 90,
    extinguisherStatus: 'normal',
    latitude: 38.119172 + (Math.random() - 0.5) * 0.05,
    longitude: 128.465386 + (Math.random() - 0.5) * 0.05,
    region: '강원',
  },
  {
    id: 11,
    name: '설악산 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 40,
    extinguisherStatus: 'normal',
    latitude: 38.119172 + (Math.random() - 0.5) * 0.05,
    longitude: 128.465386 + (Math.random() - 0.5) * 0.05,
    region: '강원',
  },
  {
    id: 12,
    name: '설악산 자동소화기 C',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 38.119172 + (Math.random() - 0.5) * 0.05,
    longitude: 128.465386 + (Math.random() - 0.5) * 0.05,
    region: '강원',
  },

  // 덕유산 (전북)
  {
    id: 13,
    name: '덕유산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 75,
    extinguisherStatus: 'normal',
    latitude: 35.85583 + (Math.random() - 0.5) * 0.05,
    longitude: 127.74583 + (Math.random() - 0.5) * 0.05,
    region: '전북',
  },
  {
    id: 14,
    name: '덕유산 자동소화기 B',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 55,
    extinguisherStatus: 'normal',
    latitude: 35.85583 + (Math.random() - 0.5) * 0.05,
    longitude: 127.74583 + (Math.random() - 0.5) * 0.05,
    region: '전북',
  },

  // 계방산 (강원)
  {
    id: 15,
    name: '계방산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 80,
    extinguisherStatus: 'normal',
    latitude: 37.758889 + (Math.random() - 0.5) * 0.05,
    longitude: 128.420946 + (Math.random() - 0.5) * 0.05,
    region: '강원',
  },

  // 속리산 (충북)
  {
    id: 16,
    name: '속리산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 70,
    extinguisherStatus: 'normal',
    latitude: 36.5380 + (Math.random() - 0.5) * 0.05,
    longitude: 127.8300 + (Math.random() - 0.5) * 0.05,
    region: '충북',
  },
  {
    id: 17,
    name: '속리산 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 25,
    extinguisherStatus: 'normal',
    latitude: 36.5380 + (Math.random() - 0.5) * 0.05,
    longitude: 127.8300 + (Math.random() - 0.5) * 0.05,
    region: '충북',
  },

  // 가야산 (경북)
  {
    id: 18,
    name: '가야산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 88,
    extinguisherStatus: 'normal',
    latitude: 35.8200 + (Math.random() - 0.5) * 0.05,
    longitude: 128.1200 + (Math.random() - 0.5) * 0.05,
    region: '경북',
  },

  // 변산반도 (전북)
  {
    id: 19,
    name: '변산반도 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 65,
    extinguisherStatus: 'normal',
    latitude: 35.6500 + (Math.random() - 0.5) * 0.05,
    longitude: 126.5000 + (Math.random() - 0.5) * 0.05,
    region: '전북',
  },

  // 월출산 (전남)
  {
    id: 20,
    name: '월출산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 72,
    extinguisherStatus: 'normal',
    latitude: 34.7700 + (Math.random() - 0.5) * 0.05,
    longitude: 126.6500 + (Math.random() - 0.5) * 0.05,
    region: '전남',
  },

  // 주왕산 (경북)
  {
    id: 21,
    name: '주왕산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 80,
    extinguisherStatus: 'normal',
    latitude: 36.4000 + (Math.random() - 0.5) * 0.05,
    longitude: 129.2000 + (Math.random() - 0.5) * 0.05,
    region: '경북',
  },

  // 태백산 (강원)
  {
    id: 22,
    name: '태백산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 90,
    extinguisherStatus: 'normal',
    latitude: 37.1000 + (Math.random() - 0.5) * 0.05,
    longitude: 128.9000 + (Math.random() - 0.5) * 0.05,
    region: '강원',
  },

  // 치악산 (강원)
  {
    id: 23,
    name: '치악산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 60,
    extinguisherStatus: 'normal',
    latitude: 37.3500 + (Math.random() - 0.5) * 0.05,
    longitude: 128.0000 + (Math.random() - 0.5) * 0.05,
    region: '강원',
  },

  // 계룡산 (충남)
  {
    id: 24,
    name: '계룡산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 70,
    extinguisherStatus: 'normal',
    latitude: 36.3500 + (Math.random() - 0.5) * 0.05,
    longitude: 127.2500 + (Math.random() - 0.5) * 0.05,
    region: '충남',
  },

  // 북한산 (서울)
  {
    id: 25,
    name: '북한산 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 85,
    extinguisherStatus: 'normal',
    latitude: 37.6585 + (Math.random() - 0.5) * 0.05,
    longitude: 126.9950 + (Math.random() - 0.5) * 0.05,
    region: '서울',
  },
  {
    id: 26,
    name: '북한산 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 35,
    extinguisherStatus: 'normal',
    latitude: 37.6585 + (Math.random() - 0.5) * 0.05,
    longitude: 126.9950 + (Math.random() - 0.5) * 0.05,
    region: '서울',
  },
  {
    id: 27,
    name: '남산 자동소화기 A',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 37.5500 + (Math.random() - 0.5) * 0.05,
    longitude: 126.9900 + (Math.random() - 0.5) * 0.05,
    region: '서울',
  },

  // 경주 국립공원 (경북)
  {
    id: 28,
    name: '경주 국립공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 92,
    extinguisherStatus: 'normal',
    latitude: 35.8000 + (Math.random() - 0.5) * 0.05,
    longitude: 129.3000 + (Math.random() - 0.5) * 0.05,
    region: '경북',
  },
  {
    id: 29,
    name: '경주 국립공원 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 45,
    extinguisherStatus: 'normal',
    latitude: 35.8000 + (Math.random() - 0.5) * 0.05,
    longitude: 129.3000 + (Math.random() - 0.5) * 0.05,
    region: '경북',
  },

  // 내장산 국립공원 (전북)
  {
    id: 30,
    name: '내장산 국립공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 78,
    extinguisherStatus: 'normal',
    latitude: 35.4700 + (Math.random() - 0.5) * 0.05,
    longitude: 126.9000 + (Math.random() - 0.5) * 0.05,
    region: '전북',
  },

  // 서울숲 (서울)
  {
    id: 31,
    name: '서울숲 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 80,
    extinguisherStatus: 'normal',
    latitude: 37.5445 + (Math.random() - 0.5) * 0.01,
    longitude: 127.0400 + (Math.random() - 0.5) * 0.01,
    region: '서울',
  },
  {
    id: 32,
    name: '서울숲 자동소화기 B',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 60,
    extinguisherStatus: 'normal',
    latitude: 37.5445 + (Math.random() - 0.5) * 0.01,
    longitude: 127.0400 + (Math.random() - 0.5) * 0.01,
    region: '서울',
  },

  // 올림픽공원 (서울)
  {
    id: 33,
    name: '올림픽공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 90,
    extinguisherStatus: 'normal',
    latitude: 37.5200 + (Math.random() - 0.5) * 0.01,
    longitude: 127.1200 + (Math.random() - 0.5) * 0.01,
    region: '서울',
  },
  {
    id: 34,
    name: '올림픽공원 자동소화기 B',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 37.5200 + (Math.random() - 0.5) * 0.01,
    longitude: 127.1200 + (Math.random() - 0.5) * 0.01,
    region: '서울',
  },

  // 태종대 공원 (부산)
  {
    id: 35,
    name: '태종대 공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 75,
    extinguisherStatus: 'normal',
    latitude: 35.0500 + (Math.random() - 0.5) * 0.01,
    longitude: 129.0800 + (Math.random() - 0.5) * 0.01,
    region: '부산',
  },
  {
    id: 36,
    name: '태종대 공원 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 40,
    extinguisherStatus: 'normal',
    latitude: 35.0500 + (Math.random() - 0.5) * 0.01,
    longitude: 129.0800 + (Math.random() - 0.5) * 0.01,
    region: '부산',
  },

  // 앞산 공원 (대구)
  {
    id: 37,
    name: '앞산 공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 88,
    extinguisherStatus: 'normal',
    latitude: 35.8300 + (Math.random() - 0.5) * 0.01,
    longitude: 128.5700 + (Math.random() - 0.5) * 0.01,
    region: '대구',
  },

  // 무등산 국립공원 (광주)
  {
    id: 38,
    name: '무등산 국립공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 95,
    extinguisherStatus: 'normal',
    latitude: 35.1000 + (Math.random() - 0.5) * 0.05,
    longitude: 126.9500 + (Math.random() - 0.5) * 0.05,
    region: '광주',
  },
  {
    id: 39,
    name: '무등산 국립공원 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 30,
    extinguisherStatus: 'normal',
    latitude: 35.1000 + (Math.random() - 0.5) * 0.05,
    longitude: 126.9500 + (Math.random() - 0.5) * 0.05,
    region: '광주',
  },

  // 과천 서울대공원 (경기)
  {
    id: 40,
    name: '과천 서울대공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 82,
    extinguisherStatus: 'normal',
    latitude: 37.4200 + (Math.random() - 0.5) * 0.01,
    longitude: 127.0000 + (Math.random() - 0.5) * 0.01,
    region: '경기',
  },
  {
    id: 41,
    name: '과천 서울대공원 자동소화기 B',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 68,
    extinguisherStatus: 'normal',
    latitude: 37.4200 + (Math.random() - 0.5) * 0.01,
    longitude: 127.0000 + (Math.random() - 0.5) * 0.01,
    region: '경기',
  },

  // 에버랜드 (경기)
  {
    id: 42,
    name: '에버랜드 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 90,
    extinguisherStatus: 'normal',
    latitude: 37.2900 + (Math.random() - 0.5) * 0.01,
    longitude: 127.2000 + (Math.random() - 0.5) * 0.01,
    region: '경기',
  },

  // 추가 공원 데이터
  // 대전 한밭수목원 (대전)
  {
    id: 43,
    name: '한밭수목원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 85,
    extinguisherStatus: 'normal',
    latitude: 36.3600 + (Math.random() - 0.5) * 0.01,
    longitude: 127.3800 + (Math.random() - 0.5) * 0.01,
    region: '대전',
  },
  {
    id: 44,
    name: '한밭수목원 자동소화기 B',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 36.3600 + (Math.random() - 0.5) * 0.01,
    longitude: 127.3800 + (Math.random() - 0.5) * 0.01,
    region: '대전',
  },

  // 광교호수공원 (경기)
  {
    id: 45,
    name: '광교호수공원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 70,
    extinguisherStatus: 'normal',
    latitude: 37.2800 + (Math.random() - 0.5) * 0.01,
    longitude: 127.0600 + (Math.random() - 0.5) * 0.01,
    region: '경기',
  },
  {
    id: 46,
    name: '광교호수공원 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 30,
    extinguisherStatus: 'normal',
    latitude: 37.2800 + (Math.random() - 0.5) * 0.01,
    longitude: 127.0600 + (Math.random() - 0.5) * 0.01,
    region: '경기',
  },

  // 순천만국가정원 (전남)
  {
    id: 47,
    name: '순천만국가정원 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 90,
    extinguisherStatus: 'normal',
    latitude: 34.9300 + (Math.random() - 0.5) * 0.01,
    longitude: 127.5300 + (Math.random() - 0.5) * 0.01,
    region: '전남',
  },
  {
    id: 48,
    name: '순천만국가정원 자동소화기 B',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 34.9300 + (Math.random() - 0.5) * 0.01,
    longitude: 127.5300 + (Math.random() - 0.5) * 0.01,
    region: '전남',
  },

  // 강릉 경포호 (강원)
  {
    id: 49,
    name: '경포호 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 80,
    extinguisherStatus: 'normal',
    latitude: 37.7900 + (Math.random() - 0.5) * 0.01,
    longitude: 128.9000 + (Math.random() - 0.5) * 0.01,
    region: '강원',
  },

  // 부산 해운대 (부산)
  {
    id: 50,
    name: '해운대 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 70,
    extinguisherStatus: 'normal',
    latitude: 35.1600 + (Math.random() - 0.5) * 0.01,
    longitude: 129.1600 + (Math.random() - 0.5) * 0.01,
    region: '부산',
  },

  // 기타 지역
  {
    id: 51,
    name: '기타 지역 자동소화기 A',
    isOnline: true,
    isFireDetected: false,
    batteryLevel: 88,
    extinguisherStatus: 'normal',
    latitude: 36.0 + (Math.random() - 0.5) * 5,
    longitude: 127.5 + (Math.random() - 0.5) * 5,
    region: '기타',
  },
  {
    id: 52,
    name: '기타 지역 자동소화기 B',
    isOnline: true,
    isFireDetected: true,
    batteryLevel: 25,
    extinguisherStatus: 'normal',
    latitude: 36.0 + (Math.random() - 0.5) * 5,
    longitude: 127.5 + (Math.random() - 0.5) * 5,
    region: '기타',
  },
  {
    id: 53,
    name: '기타 지역 자동소화기 C',
    isOnline: false,
    isFireDetected: false,
    batteryLevel: 0,
    extinguisherStatus: 'unknown',
    latitude: 36.0 + (Math.random() - 0.5) * 5,
    longitude: 127.5 + (Math.random() - 0.5) * 5,
    region: '기타',
  },
];